# -*- coding: utf-8 -*-
"""NovelAI-UI V1.2.1.ipynb 训练模型专用版 (by.库尼娅)_SakunoviEdition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j96vyskm6PLWGJ7cl6P7nWfDiVdlf7vw

Adapted from: https://colab.research.google.com/drive/1AfAmwLMd_Vx33O9IwY2TmO9wKZ8ABRRa and https://colab.research.google.com/drive/1zuK0u8UW8IKMEvVNz7lU34Qph_gS14XD#scrollTo=R-xAdMA5wxXd
"""

import os
# 这里一定会报错，不要恐慌并且无视报错继续执行
os.kill(os.getpid(), 9) # This will crash Colab (required, everything will still be intact so dont worry)

from google.colab import drive
drive.mount('/content/drive')

"""Clone webui repository"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
# %cd stable-diffusion-webui

"""Download the model from IPFS. If the quota is exceeded, you can switch to Onedrive version, or use [this](https://mapaler.github.io/GetOneDriveDirectLink/) to generate a direct link from your Onedrive."""

# Commented out IPython magic to ensure Python compatibility.
#@title Novelai-Model
!mkdir -p /content/stable-diffusion-webui/models/Stable-diffusion /content/stable-diffusion-webui/models/hypernetworks
# %cd /content/stable-diffusion-webui/models/Stable-diffusion/

# 7G animefull-final-latest (may not work on free plan)
# !curl -Lo model.ckpt https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/animefull-latest.ckpt
# !curl -Lo /content/stable-diffusion-webui/config.yaml https://cloudflare-ipfs.com/ipfs/bafybeiav3j7npiuewbel3mi32l3sidgkw54kuleosbhxmdvddbnvtfi7yu/config.yaml

# 4G animefull-final-pruned
!curl -Lo model.ckpt https://cloudflare-ipfs.com/ipfs/bafybeicpamreyp2bsocyk3hpxr7ixb2g2rnrequub3j2ahrkdxbvfbvjc4/model.ckpt
!curl -Lo /content/stable-diffusion-webui/config.yaml https://cloudflare-ipfs.com/ipfs/bafybeiav3j7npiuewbel3mi32l3sidgkw54kuleosbhxmdvddbnvtfi7yu/config.yaml

# Install VAE Weights (optional)
#!curl -Lo model.vae.pt https://cloudflare-ipfs.com/ipfs/bafybeiccldswdd3wvg57jhclcq53lvsc6gizasiblwayvhlv6eq4wow7wu/animevae.pt 

# Install hypernetwork （optional)
!curl -L https://cloudflare-ipfs.com/ipfs/bafybeiduanx2b3mcvxlwr66igcwnpfmk3nc3qgxlpwh6oq6m6pxii3f77e/_modules.tar | tar x -C /content/stable-diffusion-webui/models/hypernetworks

# Install custom embeddings (modified, optional)
# !curl -L https://cloudflare-ipfs.com/ipfs/bafybeie3hdjchxs5tz4n75bos53nhcklslguxchdurc2ynrzcfv2kwyklu/embeddings.tar | tar x -C /content/stable-diffusion-webui/embeddings

#@title Novelai-Model Onedrive version for backup
# 7G version
#!wget "http://storage.live.com/items/E79F9DDD6278815A%21287172:/novelai-latest-model.ckpt&authkey=AAv-sf_PUKZM4ho" -O /content/stable-diffusion-webui/model.ckpt

# 4G version
#!wget "http://storage.live.com/items/E79F9DDD6278815A%21287169:/novelaileak-model.ckpt&authkey=AAv-sf_PUKZM4ho" -O /content/stable-diffusion-webui/model.ckpt
#!wget "http://storage.live.com/items/E79F9DDD6278815A%21287170:/animevae.pt&authkey=AAv-sf_PUKZM4ho" -O /content/stable-diffusion-webui/model.vae.pt
#!wget "http://storage.live.com/items/E79F9DDD6278815A%21287171:/modules.zip&authkey=AAv-sf_PUKZM4ho" -O /content/stable-diffusion-webui/models/modules.zip

#!cd /content/stable-diffusion-webui/models && unzip -oj modules.zip -d hypernetworks && rm -rf modules.zip

"""Voldy doesn't explian what this does but it appears to replace the prior dependencies section, saving a few lines lmao """

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stable-diffusion-webui
!COMMANDLINE_ARGS="--exit" REQS_FILE="requirements.txt" python launch.py

"""Change into Web UI directory and download updates"""

# Commented out IPython magic to ensure Python compatibility.
# %cd stable-diffusion-webui
!git pull

#@title Install Bore Tunnel
!wget https://yun.wafuwafu.com/d/189Cloud/Storage%20Space/Sources/bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz
!tar -xf bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz
!rm -f bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz
!cp bore /usr/bin/bore
!rm -rf bore

"""Launch web ui. You will get a link to bore.pub:xxxxx, follow it."""

#!sed -i -e "125 c \ \ \ \ sd = pl_sd" /content/stable-diffusion-webui/modules/sd_models.py      #if use 7G version, turn this on.
#!python webui.py --autolaunch --precision autocast --config config.yaml & bore local 7860 --to bore.pub

!pip install tensorflow
!pip install tensorflow-io
!pip install git+https://github.com/KichangKim/DeepDanbooru.git@edf73df4cdaeea2cf00e9ac08bd8a9026b7a7b26  #egg=deepdanbooru deepdanbooru

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stable-diffusion-webui
!COMMANDLINE_ARGS="--deepdanbooru" REQS_FILE="requirements.txt" python launch.py  --config config.yaml & bore local 7860 --to bore.pub

!pip install xformers

!pip install triton

!python webui.py --autolaunch --precision autocast --config  config.yaml & bore local 7860 --to bore.pub

"""When you get the **127.0.0.1**, you should **stop** this process and run the following"""

#!sed -i -e "125 c \ \ \ \ sd = pl_sd" /content/stable-diffusion-webui/modules/sd_models.py      #if use 7G version, turn this on.
#隐藏输出项，防止页面卡顿和内存溢出。
import os, sys
class HiddenPrints:
    def __enter__(self):
        self._original_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')

    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stdout = self._original_stdout
with HiddenPrints():
#        !python webui.py --autolaunch --precision autocast --config config.yaml & bore local 7860 --to bore.pub -p xxxxx
        !python webui.py --autolaunch --precision autocast --config config.yaml & bore local 7860 --to bore.pub -p 38495

"""Brows the address : bore.pub:xxxxx

**For better quality**: steps > 28, cfg scale = 11, DDIM sampling

**Prompt**: (((best quality))),((ilustration)), ((master piece)), ((ultra-detailed)), detailed face, cute, sangonomiya kokomi,genshin impact, water, brilliant, ((portrait))

**Negative Prompt**: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, bad feet

[一些XP关键词](https://paste.ubuntu.com/p/dFBhdJR8PQ/)  
[ExHentai tag翻译](https://github.com/scooderic/exhentai-tags-chinese-translation)  
[Prompt交流网站(带图) ](https://seesaawiki.jp/nai_ch/d/%B1%D3%BE%A7%C1%B4%CA%B8)

commands for ***after*** you have gotten done with a session
============================================================================

下载到本地  
Zip images for downloading on local drive (click the folder icon on the left, the one below {x})
"""

!zip -r /content/stable-diffusion-webui /content/stable-diffusion-webui/outputs

"""保存到谷歌网盘  
Save images to Google Drive **Warning: this will cause google to scan your drive, so if you intend to use this and worry about that kind of stuff, probablly just set this up on a clean account that's just for this colab**
"""

from google.colab import drive # type: ignore

try:
   drive_path = "/content/drive"
   drive.mount(drive_path,force_remount=False)
except:
   print("...error mounting drive or with drive path variables")

!cp -r "/content/stable-diffusion-webui/outputs" "/content/drive/MyDrive"